name: 💬 Question
description: Ask a question about the module.
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please make sure that you have read through our [documentation](https://mei-nuxt3-module-starter.toantranmei.com) and existing [issues](https://github.com/nuxt/toantranmei/mei-nuxt3-module-starter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
